souffle: souffle::ast::transform::ReorderLiteralsTransformer Class Reference
souffle::ast::transform::ReorderLiteralsTransformer Class Reference
Transformation pass to reorder body literals.
#include <ReorderLiterals.h>
Public Member Functions
ReorderLiteralsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Static Public Member Functions
static sips_t getSipsFunction (const std::string &sipsChosen)
Returns a SIPS function based on the SIPS option provided.
static Clause * reorderClauseWithSips (sips_t sipsFunction, const Clause *clause)
Reorder the clause based on a given SIPS function.
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Static Private Member Functions
static std::vector< unsigned int > getOrderingAfterSIPS (sips_t sipsFunction, const Clause *clause)
Determines the new ordering of a clause after the given SIPS is applied.
Detailed Description
Transformation pass to reorder body literals.
Definition at line 41 of file ReorderLiterals.h.
Member Function Documentation
clone()
ReorderLiteralsTransformer* souffle::ast::transform::ReorderLiteralsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 47 of file ReorderLiterals.h.
References getOrderingAfterSIPS(), getSipsFunction(), reorderClauseWithSips(), and transform().
{
         return new ReorderLiteralsTransformer();
     }
getName()
std::string souffle::ast::transform::ReorderLiteralsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 43 of file ReorderLiterals.h.
{
         return "ReorderLiteralsTransformer";
     }
getOrderingAfterSIPS()
std::vector< unsigned int > souffle::ast::transform::ReorderLiteralsTransformer::getOrderingAfterSIPS (sips_t sipsFunction, const Clause * clause) static private
Determines the new ordering of a clause after the given SIPS is applied.
Parameters
sipsFunction SIPS metric to use
clause clause to reorder
Returns
the vector of new positions; v[i] = j iff atom j moves to pos i
Definition at line 267 of file ReorderLiterals.cpp.
References souffle::ast::BindingStore::bindVariableStrongly(), and souffle::ast::Atom::getArguments().
Referenced by clone(), and reorderClauseWithSips().
{
     BindingStore bindingStore(clause);
     auto atoms = getBodyLiterals<Atom>(*clause);
     std::vector<unsigned int> newOrder(atoms.size());
     unsigned int numAdded = 0;
     while (numAdded < atoms.size()) {
         // grab the next atom, based on the SIPS function
         unsigned int nextIdx = sipsFunction(atoms, bindingStore);
         Atom* nextAtom = atoms[nextIdx];
         // set all arguments that are variables as bound
         // note: arguments that are functors, etc., do not newly bind anything
         for (Argument* arg : nextAtom->getArguments()) {
             if (auto* var = dynamic_cast<ast::Variable*>(arg)) {
                 bindingStore.bindVariableStrongly(var->getName());
             }
         }
         newOrder[numAdded] = nextIdx;  // add to the ordering
         atoms[nextIdx] = nullptr;      // mark as done
         numAdded++;                    // move on
     }
     return newOrder;
 }
getSipsFunction()
sips_t souffle::ast::transform::ReorderLiteralsTransformer::getSipsFunction (const std::string & sipsChosen) static
Returns a SIPS function based on the SIPS option provided.
Definition at line 40 of file ReorderLiterals.cpp.
References souffle::ast::Atom::getArity(), i, souffle::ast::isProposition(), lhs, rhs, and souffle::ast::visitDepthFirst().
Referenced by clone(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), and transform().
{
     // --- Create the appropriate SIPS function ---
     // Each SIPS function has a priority metric (e.g. max-bound atoms).
     // Arguments:
     //      - a vector of atoms to choose from (nullpointers in the vector will be ignored)
     //      - the set of variables bound so far
     // Returns: the index of the atom maximising the priority metric
     sips_t getNextAtomSips;
     if (sipsChosen == "naive") {
         // Goal: choose the first atom with at least one bound argument, or with no arguments
         getNextAtomSips = [&](std::vector<Atom*> atoms, const BindingStore& bindingStore) {
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const Atom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // no arguments
                     return i;
                 }
                 if (bindingStore.numBoundArguments(currAtom) >= 1) {
                     // at least one bound argument
                     return i;
                 }
             }
             // none found; choose the first non-null
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 if (atoms[i] != nullptr) {
                     return i;
                 }
             }
             // fall back to the first
             return 0U;
         };
     } else if (sipsChosen == "all-bound") {
         // Goal: prioritise atoms with all arguments bound
         getNextAtomSips = [&](std::vector<Atom*> atoms, const BindingStore& bindingStore) {
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const Atom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // no arguments, so all are trivially bound
                     return i;
                 }
                 int arity = currAtom->getArity();
                 int numBound = bindingStore.numBoundArguments(currAtom);
                 if (numBound == arity) {
                     // all arguments are bound!
                     return i;
                 }
             }
             // none found; choose the first non-null
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 if (atoms[i] != nullptr) {
                     return i;
                 }
             }
             // fall back to the first
             return 0U;
         };
     } else if (sipsChosen == "max-bound") {
         // Goal: choose the atom with the maximum number of bound variables
         //       - exception: propositions should be prioritised
         getNextAtomSips = [&](std::vector<Atom*> atoms, const BindingStore& bindingStore) {
             int currMaxBound = -1;
             unsigned int currMaxIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const Atom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions should be prioritised
                     return i;
                 }
                 int numBound = bindingStore.numBoundArguments(currAtom);
                 if (numBound > currMaxBound) {
                     currMaxBound = numBound;
                     currMaxIdx = i;
                 }
             }
             return currMaxIdx;
         };
     } else if (sipsChosen == "max-ratio") {
         // Goal: choose the atom with the maximum ratio of bound to unbound
         getNextAtomSips = [&](std::vector<Atom*> atoms, const BindingStore& bindingStore) {
             auto isLargerRatio = [&](std::pair<int, int> lhs, std::pair<int, int> rhs) {
                 return (lhs.first * rhs.second > lhs.second * rhs.first);
             };
             auto currMaxRatio = std::pair<int, int>(-1, 1);  // set to -1
             unsigned int currMaxIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const Atom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions are as bound as possible
                     return i;
                 }
                 int numBound = bindingStore.numBoundArguments(currAtom);
                 int numArgs = currAtom->getArity();
                 auto currRatio = std::pair<int, int>(numBound, numArgs);
                 if (isLargerRatio(currRatio, currMaxRatio)) {
                     currMaxRatio = currRatio;
                     currMaxIdx = i;
                 }
             }
             return currMaxIdx;
         };
     } else if (sipsChosen == "least-free") {
         // Goal: choose the atom with the least number of unbound arguments
         getNextAtomSips = [&](std::vector<Atom*> atoms, const BindingStore& bindingStore) {
             int currLeastFree = -1;
             unsigned int currLeastIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const Atom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions have 0 unbound arguments, which is minimal
                     return i;
                 }
                 int numBound = bindingStore.numBoundArguments(currAtom);
                 int numFree = currAtom->getArity() - numBound;
                 if (currLeastFree == -1 || numFree < currLeastFree) {
                     currLeastFree = numFree;
                     currLeastIdx = i;
                 }
             }
             return currLeastIdx;
         };
     } else if (sipsChosen == "least-free-vars") {
         // Goal: choose the atom with the least amount of unbound variables
         getNextAtomSips = [&](std::vector<Atom*> atoms, const BindingStore& bindingStore) {
             int currLeastFree = -1;
             unsigned int currLeastIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const Atom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions have 0 unbound variables, which is minimal
                     return i;
                 }
                 // use a set to hold all free variables to avoid double-counting
                 std::set<std::string> freeVars;
                 visitDepthFirst(*currAtom, [&](const ast::Variable& var) {
                     if (bindingStore.isBound(var.getName())) {
                         freeVars.insert(var.getName());
                     }
                 });
                 int numFreeVars = freeVars.size();
                 if (currLeastFree == -1 || numFreeVars < currLeastFree) {
                     currLeastFree = numFreeVars;
                     currLeastIdx = i;
                 }
             }
             return currLeastIdx;
         };
     } else if (sipsChosen == "ast2ram") {
         return getSipsFunction("all-bound");
     } else {
         // chosen SIPS is not implemented, so keep the same order
         // Goal: leftmost atom first
         getNextAtomSips = [&](std::vector<Atom*> atoms, const BindingStore& /* bindingStore */) {
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 if (atoms[i] == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 return i;
             }
             // fall back to the first
             return 0U;
         };
     }
     return getNextAtomSips;
 }
reorderClauseWithSips()
Clause * souffle::ast::transform::ReorderLiteralsTransformer::reorderClauseWithSips (sips_t sipsFunction, const Clause * clause) static
Reorder the clause based on a given SIPS function.
Parameters
sipsFunction SIPS metric to use
clause clause to reorder
Returns
nullptr if no change, otherwise a new reordered clause
Definition at line 295 of file ReorderLiterals.cpp.
References souffle::ast::Clause::getExecutionPlan(), getOrderingAfterSIPS(), i, and souffle::ast::reorderAtoms().
Referenced by clone(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), and transform().
{
     // ignore clauses with fixed execution plans
     if (clause->getExecutionPlan() != nullptr) {
         return nullptr;
     }
     // get the ordering corresponding to the SIPS
     std::vector<unsigned int> newOrdering = getOrderingAfterSIPS(sipsFunction, clause);
     // check if we need a change
     bool changeNeeded = false;
     for (unsigned int i = 0; i < newOrdering.size(); i++) {
         if (newOrdering[i] != i) {
             changeNeeded = true;
         }
     }
     // reorder if needed
     return changeNeeded ? reorderAtoms(clause, newOrdering) : nullptr;
 }
transform()
bool souffle::ast::transform::ReorderLiteralsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 316 of file ReorderLiterals.cpp.
References souffle::ast::Program::addClause(), souffle::Global::config(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::Atom::getArity(), souffle::ast::Program::getClauses(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Atom::getQualifiedName(), getSipsFunction(), i, souffle::ast::isProposition(), souffle::ast::Program::removeClause(), and reorderClauseWithSips().
Referenced by clone().
{
     bool changed = false;
     Program& program = *translationUnit.getProgram();
     // --- SIPS-based static reordering ---
     // ordering is based on the given SIPS
     // default SIPS to choose is 'all-bound'
     std::string sipsChosen = "all-bound";
     if (Global::config().has("SIPS")) {
         sipsChosen = Global::config().get("SIPS");
     }
     auto sipsFunction = getSipsFunction(sipsChosen);
     // literal reordering is a rule-local transformation
     std::vector<Clause*> clausesToRemove;
     for (Clause* clause : program.getClauses()) {
         Clause* newClause = reorderClauseWithSips(sipsFunction, clause);
         if (newClause != nullptr) {
             // reordering needed - swap around
             clausesToRemove.push_back(clause);
             program.addClause(Own<Clause>(newClause));
         }
     }
     changed |= !clausesToRemove.empty();
     for (auto* clause : clausesToRemove) {
         program.removeClause(clause);
     }
     // --- profile-guided reordering ---
     if (Global::config().has("profile-use")) {
         // parse supplied profile information
         auto* profileUse = translationUnit.getAnalysis<analysis::ProfileUseAnalysis>();
         auto profilerSips = [&](std::vector<Atom*> atoms, const BindingStore& bindingStore) {
             // Goal: reorder based on the given profiling information
             // Metric: cost(atom_R) = log(|atom_R|) * #free/#args
             //         - exception: propositions are prioritised
             double currOptimalVal = -1;
             unsigned int currOptimalIdx = 0U;
             bool set = false;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const Atom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // prioritise propositions
                     return i;
                 }
                 // calculate log(|R|) * #free/#args
                 int numBound = bindingStore.numBoundArguments(currAtom);
                 int numArgs = currAtom->getArity();
                 int numFree = numArgs - numBound;
                 double value = log(profileUse->getRelationSize(currAtom->getQualifiedName()));
                 value *= (numFree * 1.0) / numArgs;
                 if (!set || value < currOptimalVal) {
                     set = true;
                     currOptimalVal = value;
                     currOptimalIdx = i;
                 }
             }
             return currOptimalIdx;
         };
         // change the ordering of literals within clauses
         std::vector<Clause*> clausesToRemove;
         for (Clause* clause : program.getClauses()) {
             Clause* newClause = reorderClauseWithSips(profilerSips, clause);
             if (newClause != nullptr) {
                 // reordering needed - swap around
                 clausesToRemove.push_back(clause);
                 program.addClause(Own<Clause>(newClause));
             }
         }
         changed |= !clausesToRemove.empty();
         for (auto* clause : clausesToRemove) {
             program.removeClause(clause);
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ReorderLiterals.h
ast/transform/ReorderLiterals.cpp